# GitHub Secret Scanning Configuration
# ====================================
# This file configures GitHub's push protection for secrets.
# When enabled, GitHub will block pushes containing detected secrets.
#
# Documentation: https://docs.github.com/en/code-security/secret-scanning

# Custom patterns to detect (in addition to GitHub's built-in patterns)
paths-ignore:
  # Ignore example files
  - '**/*.example'
  - '**/*.example.*'
  - '**/example.*'

  # Ignore test files with mock data
  - '**/__tests__/**'
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/jest.setup.*'

  # Ignore documentation
  - 'docs/**'
  - '**/*.md'
