import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  Alert,
  ScrollView,
  Keyboard,
  ActivityIndicator,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { COLORS } from '@/constants/colors';
import { ScreenErrorBoundary } from '@/components/ErrorBoundary';
import { NetworkGuard } from '@/components/NetworkGuard';
import type { RootStackParamList } from '@/navigation/routeParams';
import type { StackScreenProps } from '@react-navigation/stack';

type AddMoneyScreenProps = StackScreenProps<RootStackParamList, 'AddMoney'>;

// Preset amounts for quick selection
const PRESET_AMOUNTS = [50, 100, 250, 500, 1000];

function AddMoneyScreen({ navigation }: AddMoneyScreenProps) {
  const { t } = useTranslation();
  const insets = useSafeAreaInsets();
  const [amount, setAmount] = useState('');
  const [selectedMethod, setSelectedMethod] = useState<'card' | 'bank' | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const MIN_AMOUNT = 10;
  const MAX_AMOUNT = 10000;

  const handleAmountChange = (value: string) => {
    // Only allow numbers and comma/period
    const cleaned = value.replace(/[^0-9.,]/g, '');
    setAmount(cleaned);
  };

  const handlePresetSelect = (preset: number) => {
    setAmount(preset.toString());
  };

  const handleAddMoney = async () => {
    Keyboard.dismiss();
    const numericAmount = parseFloat(amount.replace(',', '.'));

    if (!selectedMethod) {
      Alert.alert(
        t('addMoney.selectMethod', 'Yöntem Seçin'),
        t('addMoney.selectMethodMessage', 'Lütfen bir ödeme yöntemi seçin.')
      );
      return;
    }

    if (isNaN(numericAmount) || numericAmount < MIN_AMOUNT) {
      Alert.alert(
        t('addMoney.invalidAmount', 'Geçersiz Tutar'),
        t('addMoney.minAmountMessage', `Minimum yükleme tutarı ${MIN_AMOUNT} TL'dir.`)
      );
      return;
    }

    if (numericAmount > MAX_AMOUNT) {
      Alert.alert(
        t('addMoney.limitExceeded', 'Limit Aşıldı'),
        t('addMoney.maxAmountMessage', `Maksimum yükleme tutarı ${MAX_AMOUNT} TL'dir.`)
      );
      return;
    }

    setIsSubmitting(true);

    try {
      // Navigate to PayTR WebView for card payment
      if (selectedMethod === 'card') {
        navigation.navigate('PayTRWebView', {
          iframeToken: '', // Will be generated by backend
          merchantOid: `wallet_${Date.now()}`,
          amount: numericAmount,
          currency: 'TRY',
          isTestMode: __DEV__,
        });
      } else {
        // Bank transfer - show instructions
        Alert.alert(
          t('addMoney.bankTransfer', 'Banka Havalesi'),
          t(
            'addMoney.bankTransferMessage',
            'Banka havalesi talimatları e-posta adresinize gönderilecek.'
          ),
          [{ text: t('common.ok', 'Tamam'), onPress: () => navigation.goBack() }]
        );
      }
    } catch {
      Alert.alert(
        t('common.error', 'Hata'),
        t('addMoney.errorMessage', 'İşlem sırasında bir hata oluştu.')
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <ScreenErrorBoundary>
      <NetworkGuard>
        <View style={[styles.container, { paddingTop: insets.top }]}>
          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity
              onPress={() => navigation.goBack()}
              style={styles.backButton}
            >
              <Ionicons name="arrow-back" size={24} color={COLORS.text.primary} />
            </TouchableOpacity>
            <Text style={styles.headerTitle}>
              {t('addMoney.title', 'Para Yükle')}
            </Text>
            <View style={styles.headerSpacer} />
          </View>

          <ScrollView
            style={styles.content}
            showsVerticalScrollIndicator={false}
            keyboardShouldPersistTaps="handled"
          >
            {/* Amount Input */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>
                {t('addMoney.amount', 'Tutar')}
              </Text>
              <View style={styles.amountInputContainer}>
                <Text style={styles.currencySymbol}>₺</Text>
                <TextInput
                  style={styles.amountInput}
                  value={amount}
                  onChangeText={handleAmountChange}
                  keyboardType="decimal-pad"
                  placeholder="0"
                  placeholderTextColor={COLORS.text.muted}
                />
              </View>
            </View>

            {/* Preset Amounts */}
            <View style={styles.presetContainer}>
              {PRESET_AMOUNTS.map((preset) => (
                <TouchableOpacity
                  key={preset}
                  style={[
                    styles.presetButton,
                    amount === preset.toString() && styles.presetButtonActive,
                  ]}
                  onPress={() => handlePresetSelect(preset)}
                >
                  <Text
                    style={[
                      styles.presetText,
                      amount === preset.toString() && styles.presetTextActive,
                    ]}
                  >
                    ₺{preset}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>

            {/* Payment Methods */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>
                {t('addMoney.paymentMethod', 'Ödeme Yöntemi')}
              </Text>

              <TouchableOpacity
                style={[
                  styles.methodCard,
                  selectedMethod === 'card' && styles.methodCardActive,
                ]}
                onPress={() => setSelectedMethod('card')}
              >
                <View style={styles.methodIcon}>
                  <MaterialCommunityIcons
                    name="credit-card"
                    size={24}
                    color={
                      selectedMethod === 'card'
                        ? COLORS.brand.primary
                        : COLORS.text.secondary
                    }
                  />
                </View>
                <View style={styles.methodInfo}>
                  <Text style={styles.methodTitle}>
                    {t('addMoney.creditCard', 'Kredi/Banka Kartı')}
                  </Text>
                  <Text style={styles.methodDesc}>
                    {t('addMoney.instantDeposit', 'Anında yükleme')}
                  </Text>
                </View>
                <View
                  style={[
                    styles.radio,
                    selectedMethod === 'card' && styles.radioActive,
                  ]}
                >
                  {selectedMethod === 'card' && (
                    <View style={styles.radioInner} />
                  )}
                </View>
              </TouchableOpacity>

              <TouchableOpacity
                style={[
                  styles.methodCard,
                  selectedMethod === 'bank' && styles.methodCardActive,
                ]}
                onPress={() => setSelectedMethod('bank')}
              >
                <View style={styles.methodIcon}>
                  <MaterialCommunityIcons
                    name="bank"
                    size={24}
                    color={
                      selectedMethod === 'bank'
                        ? COLORS.brand.primary
                        : COLORS.text.secondary
                    }
                  />
                </View>
                <View style={styles.methodInfo}>
                  <Text style={styles.methodTitle}>
                    {t('addMoney.bankTransfer', 'Banka Havalesi')}
                  </Text>
                  <Text style={styles.methodDesc}>
                    {t('addMoney.bankTransferTime', '1-2 iş günü')}
                  </Text>
                </View>
                <View
                  style={[
                    styles.radio,
                    selectedMethod === 'bank' && styles.radioActive,
                  ]}
                >
                  {selectedMethod === 'bank' && (
                    <View style={styles.radioInner} />
                  )}
                </View>
              </TouchableOpacity>
            </View>

            {/* Info */}
            <View style={styles.infoCard}>
              <MaterialCommunityIcons
                name="shield-check"
                size={20}
                color={COLORS.feedback.success}
              />
              <Text style={styles.infoText}>
                {t(
                  'addMoney.securePayment',
                  'Tüm ödemeler 256-bit SSL ile güvenle korunmaktadır.'
                )}
              </Text>
            </View>
          </ScrollView>

          {/* Submit Button */}
          <View style={[styles.footer, { paddingBottom: insets.bottom + 16 }]}>
            <TouchableOpacity
              style={[
                styles.submitButton,
                (!amount || !selectedMethod || isSubmitting) &&
                  styles.submitButtonDisabled,
              ]}
              onPress={handleAddMoney}
              disabled={!amount || !selectedMethod || isSubmitting}
            >
              {isSubmitting ? (
                <ActivityIndicator color={COLORS.text.inverse} />
              ) : (
                <Text style={styles.submitButtonText}>
                  {t('addMoney.continue', 'Devam Et')}
                </Text>
              )}
            </TouchableOpacity>
          </View>
        </View>
      </NetworkGuard>
    </ScreenErrorBoundary>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  headerSpacer: {
    width: 40,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text.secondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background.secondary,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  currencySymbol: {
    fontSize: 32,
    fontWeight: '700',
    color: COLORS.text.primary,
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: '700',
    color: COLORS.text.primary,
    padding: 0,
  },
  presetContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  presetButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: COLORS.background.secondary,
    borderWidth: 1,
    borderColor: COLORS.border.light,
  },
  presetButtonActive: {
    backgroundColor: COLORS.brand.primary,
    borderColor: COLORS.brand.primary,
  },
  presetText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  presetTextActive: {
    color: COLORS.text.inverse,
  },
  methodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background.secondary,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  methodCardActive: {
    borderColor: COLORS.brand.primary,
    backgroundColor: `${COLORS.brand.primary}10`,
  },
  methodIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.background.tertiary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  methodInfo: {
    flex: 1,
  },
  methodTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text.primary,
    marginBottom: 2,
  },
  methodDesc: {
    fontSize: 13,
    color: COLORS.text.secondary,
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: COLORS.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: {
    borderColor: COLORS.brand.primary,
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.brand.primary,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${COLORS.feedback.success}15`,
    borderRadius: 12,
    padding: 14,
    gap: 10,
    marginBottom: 24,
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.feedback.success,
    lineHeight: 18,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border.light,
  },
  submitButton: {
    backgroundColor: COLORS.brand.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.5,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text.inverse,
  },
});

export default AddMoneyScreen;
