/**
 * Mock for @sentry/react-native
 */
module.exports = {
  init: jest.fn(),
  captureException: jest.fn(),
  captureMessage: jest.fn(),
  captureEvent: jest.fn(),
  captureFeedback: jest.fn(),
  addBreadcrumb: jest.fn(),
  addIntegration: jest.fn(),
  setContext: jest.fn(),
  setExtra: jest.fn(),
  setExtras: jest.fn(),
  setTag: jest.fn(),
  setTags: jest.fn(),
  setUser: jest.fn(),
  startInactiveSpan: jest.fn(),
  startSpan: jest.fn(),
  startSpanManual: jest.fn(),
  getActiveSpan: jest.fn(),
  getRootSpan: jest.fn(),
  withActiveSpan: jest.fn(),
  suppressTracing: jest.fn(),
  spanToJSON: jest.fn(),
  spanIsSampled: jest.fn(),
  setMeasurement: jest.fn(),
  getCurrentScope: jest.fn(() => ({
    setUser: jest.fn(),
    setTag: jest.fn(),
    setExtra: jest.fn(),
    addBreadcrumb: jest.fn(),
  })),
  getGlobalScope: jest.fn(() => ({
    setUser: jest.fn(),
    setTag: jest.fn(),
    setExtra: jest.fn(),
  })),
  getIsolationScope: jest.fn(() => ({
    setUser: jest.fn(),
    setTag: jest.fn(),
    setExtra: jest.fn(),
  })),
  getClient: jest.fn(),
  setCurrentClient: jest.fn(),
  addEventProcessor: jest.fn(),
  lastEventId: jest.fn(),
  withScope: jest.fn((callback) =>
    callback({
      setTag: jest.fn(),
      setExtra: jest.fn(),
      setContext: jest.fn(),
      addBreadcrumb: jest.fn(),
      setLevel: jest.fn(),
    }),
  ),
  Scope: jest.fn().mockImplementation(() => ({
    setTag: jest.fn(),
    setExtra: jest.fn(),
    setContext: jest.fn(),
  })),
  Severity: {
    Fatal: 'fatal',
    Error: 'error',
    Warning: 'warning',
    Info: 'info',
    Debug: 'debug',
  },
  ReactNativeTracing: jest.fn(),
  ReactNavigationInstrumentation: jest.fn().mockImplementation(() => ({
    registerNavigationContainer: jest.fn(),
  })),
  wrap: (component) => component,
  nativeCrash: jest.fn(),
  flush: jest.fn().mockResolvedValue(true),
  close: jest.fn().mockResolvedValue(true),
};
