// Mock design tokens for testing
module.exports = {
  __esModule: true,
  colors: {
    primary: {
      main: '#7C3AED',
      light: '#A78BFA',
      dark: '#5B21B6',
    },
    secondary: {
      main: '#10B981',
      light: '#34D399',
      dark: '#059669',
    },
    background: {
      primary: '#FFFFFF',
      secondary: '#F3F4F6',
      tertiary: '#E5E7EB',
    },
    text: {
      primary: '#1F2937',
      secondary: '#6B7280',
      tertiary: '#9CA3AF',
      inverse: '#FFFFFF',
    },
    border: {
      primary: '#E5E7EB',
      secondary: '#D1D5DB',
    },
    status: {
      success: '#10B981',
      error: '#EF4444',
      warning: '#F59E0B',
      info: '#3B82F6',
    },
    semantic: {
      link: '#7C3AED',
    },
    overlay: 'rgba(0, 0, 0, 0.5)',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    '3xl': 64,
    '4xl': 96,
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
  typography: {
    fontFamily: {
      primary: 'System',
      secondary: 'System',
      mono: 'Courier',
    },
    fontSize: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
      '5xl': 48,
      '6xl': 60,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.5,
      relaxed: 1.75,
      loose: 2,
    },
    fontWeight: {
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
    },
    letterSpacing: {
      tight: -0.5,
      normal: 0,
      wide: 0.5,
      wider: 1,
    },
    styles: {
      h1: {
        fontSize: 48,
        lineHeight: 1.2,
        fontWeight: '700',
        letterSpacing: -0.5,
      },
      h2: {
        fontSize: 36,
        lineHeight: 1.2,
        fontWeight: '700',
        letterSpacing: -0.5,
      },
      h3: {
        fontSize: 30,
        lineHeight: 1.3,
        fontWeight: '600',
        letterSpacing: 0,
      },
      h4: {
        fontSize: 24,
        lineHeight: 1.4,
        fontWeight: '600',
        letterSpacing: 0,
      },
      h5: {
        fontSize: 20,
        lineHeight: 1.4,
        fontWeight: '600',
        letterSpacing: 0,
      },
      h6: {
        fontSize: 18,
        lineHeight: 1.5,
        fontWeight: '600',
        letterSpacing: 0,
      },
      body1: {
        fontSize: 16,
        lineHeight: 1.5,
        fontWeight: '400',
        letterSpacing: 0,
      },
      body2: {
        fontSize: 14,
        lineHeight: 1.5,
        fontWeight: '400',
        letterSpacing: 0,
      },
      caption: {
        fontSize: 12,
        lineHeight: 1.5,
        fontWeight: '400',
        letterSpacing: 0.5,
      },
      button: {
        fontSize: 16,
        lineHeight: 1.5,
        fontWeight: '600',
        letterSpacing: 0.5,
      },
    },
  },
};
