export const ErrorCodes = {
  OK: 'OK',

  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  RLS_DENIED: 'RLS_DENIED',

  PLAN_UPGRADE_REQUIRED: 'PLAN_UPGRADE_REQUIRED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',

  INVALID_PARAMS: 'INVALID_PARAMS',

  RATE_LIMITED: 'RATE_LIMITED',

  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  SELF_TRANSFER_FORBIDDEN: 'SELF_TRANSFER_FORBIDDEN',
  ESCROW_REQUIRED: 'ESCROW_REQUIRED',
  CONTRIBUTOR_LIMIT_REACHED: 'CONTRIBUTOR_LIMIT_REACHED',
  IDP_CONFLICT: 'IDP_CONFLICT',

  INVALID_STATE: 'INVALID_STATE',
  NOT_FOUND: 'NOT_FOUND',

  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
